### ISSUE TITLE
SSL is not working out of the box

### ISSUE THREAD

**Issue by spland30** [yandex-qatools/juseppe#34]
Getting this error when I try to configure the update center to use SSL. I have changed the default update center in Jenkins to point to an internal update center. Any ideas?

Running Jenkins 2.5 on Ubuntu
```
javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at sun.security.ssl.InputRecord.handleUnknownRecord(InputRecord.java:710)
	at sun.security.ssl.InputRecord.read(InputRecord.java:527)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at 
```

**Comment by lanwen** [comment]
How you exactly use it? If you want to use https, you need a frontend before juseppe - u can use nginx for this purposes

**Comment by spland30** [comment]
Thanks. I added Nginx and it seems to work now. Is this in the documentation anywhere?

**Comment by lanwen** [comment]
This is standard approach to organize https on service without build-in support
