### ISSUE TITLE
apache reverse proxy between Jenkins and Juseppe.

### ISSUE THREAD

**Issue by pcooke2002** [yandex-qatools/juseppe#39]
Hello

Juseppe is showing that Jenkins is trying to connect.   some success  

Corporate security policy requires I place an apache based reverse proxy between on the Juseppe  server and only allow TLS1.2 between the Jenkins and Juseppe.   

- Juseppe is using a CERT provided by my corporate CA.  
- All Java installs are have the corporate CA cert in the keytool.
- Jenkins is connecting to other corporate resources that using Apache reverse proxy (I am confident Java key tool has corporate CA cert properly configured).
- I can use IE, chrome, and FireFox to browse to the reverse proxied SSL URL and get NO errors in any of the browsers

When testing out the connection to Juseppe I am getting:   

`31-May-2018 08:57:14.151 SEVERE [Handling POST /jenkins/pluginManager/checkUpdatesServer from #.#.#.# : ajp-apr-127.0.0.1-8009-exec-1643] hudson.model.UpdateSite.updateData ERROR: Signature verification failed in Update site with own cert for juseppe <a href='#' class='showDetails'>
	(show details)</a><pre style='display:none'>java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors<br>  
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:154)<br>
	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:80)<br>
	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292)<br>
	at org.jvnet.hudson.crypto.CertificateUtil.validatePath(CertificateUtil.java:93)<br>
	at jenkins.util.JSONSignatureValidator.verifySignature(JSONSignatureValidator.java:78)<br>
	at hudson.model.UpdateSite.verifySignature(UpdateSite.java:254)<br>
	..... rest of stack trace not informative`

Hoping you might have some suggestion on what might cause

**Comment by pcooke2002** [comment]
this is not an issue.  It was an incorrect system configuration
